In [ ]:
Lets find out the cummulative sum using NumPy

In [3]:
#Run the following code

import numpy as np

mat1 = np.array([[2, 5, 6, 5],[4, 8, 6, 5]])

mean_mat1=np.mean(mat1, axis=0) #np.mean() used to find the mean of matrix/array.
mean_mat2=np.mean(mat1, axis=1)

cum_sum= np.cumsum(mat1, axis=1) #the axis is 1, it implies that the function need to be deployed across columns.
cum_sum1= np.cumsum(mat1, axis=0) #the axis is 0, it implies that the function need to be deployed across rows.

print(cum_sum)
print(cum_sum1)

#Considering mat1 is the data for literacy rates
#cummulative sum of literacy rates of every quater each year is cum_sum
#we will find out the quaters for which this sum is greater or equal to 8

print(cum_sum>=8)
print(cum_sum1>=8)

print(mean_mat1)
print(mean_mat2)


[[ 2  7 13 18]
 [ 4 12 18 23]]
[[ 2  5  6  5]
 [ 6 13 12 10]]
[[False False  True  True]
 [False  True  True  True]]
[[False False False False]
 [False  True  True  True]]
[3.  6.5 6.  5. ]
[4.5  5.75]


In [8]:
#Run the Following code

import numpy as np

new_arr=[]
mat = np.array([['abc','A'],['def','B'],['ghi','C'],['jkl','D']])
arr = np.array(['abc','dfe','ghi','kjl'])
 

arr2 = np.array([90, 14, 24, 13, 13, 590, 0, 45, 16, 50]) #Find the top 4 maximun values
arr2_max= np.argpartition(arr2, -4)[-4:]

new_mat1= np.diag([4,5,6],1) 
arr1= np.arange(11)

 
arr3 = np.array([10,55,22,3,6,44,9,54]) #Find the number nearest to 50
nearest_to = 50


for i in range(0,len(mat)):
    if mat[i][0]==arr[i]:
        new_arr.append(mat[i][1])
        
for i in range (0,11):
    if arr1[i] in range(7,10):
        arr1[i]=arr1[i]*(-1)



print(new_arr)
print(new_mat1)  
print(arr1)
print(arr2[arr2_max])
print(arr3[np.abs(arr3-nearest_to).argmin()])


['A', 'C']
[[0 4 0 0]
 [0 0 5 0]
 [0 0 0 6]
 [0 0 0 0]]
[ 0  1  2  3  4  5  6 -7 -8 -9 10]
[ 45  50 590  90]
54


In [10]:
print(np.linspace(0, 10, 5, dtype = np.float64))

[ 0.   2.5  5.   7.5 10. ]


In [11]:
print(np.arange(0, 10, 5, dtype = np.float64))

[0. 5.]
