In [ ]:
Introdution to Numpy:
#prerequistes--> Fundamentals of Python programming

Lets dive right in with understanding the basics of Numpy, Assuming you are familiar with python programming.

Numpy is most commonly used Library for Numerical operations/Scientific computations. Its like a major library with similar
importance given to Pandas, Matplotlib, Scikit-Learn etc. Lets just focus on Numpy for now then we can check out the rest later.
So Numpy.. How do you use it?Lets Understand the below problem statement.

In [ ]:
Consider a list--> 
lst=[5,10,15,20,100]

Problem statement - add element with 5 in the above list
#expected output

lst=[10,15,20,25,105]

So how to do you it ?
Classic solution to this will be to pick each element out and add 5 to it and then append it in a new list. Pretty boring
way of doing it. With Numpy this becomes easier.

In [2]:
 #Run the following code
    
import numpy as np
lst=[5,10,15,20,100]
arr=np.array(lst)
print(arr + 5)

#expected output
#lst=[10,15,20,25,105]

[ 10  15  20  25 105]


In [ ]:
NumPy supports vectorized operations such as elements addition, subtraction etc, which is not the case with basic lists.
Lets see few more examples of basic NumPy operations.

In [4]:
#Run the following code

lst = [1, 2, 3, 'text', True, 3+2j]
arr=np.array(lst)
print(type(arr[0]),type(arr[4]), type(arr[5]))

#expected output
#<class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.str_'>

<class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.str_'>


In [ ]:
Explanation for the the above problem it that a heterogeneous python inbuilt list is comparatively slow to process as 
compared with NumPy nd-array because of the fact that Python has to store type information for each element and accordingly have
to take extra time while operating on each element.
However, NumPy array works with a similar datatype and hence show a significant boost in the processing time.

Lets see another easy understanding usage of NumPy.

In [ ]:
Now lets say I want to find out the byte size of the bellow list. 

lst = [56, 45, 12, 6]


In [5]:
# Run the following code

lst = [56, 45, 12, 6]
arr = np.array(lst)
print(arr.nbytes)

#expected output: 16

16


In [ ]:
Python list usually have high memory size due to storing information for each pointer as well as to an object they are
pointing to. But with NumPy array stores uniform values. Uniform as in remaining the same in all cases and distinctive.

Lets try to dive in more with NumPy array to understand its usage as part of Python's Library.

In [ ]:
NumPy object creation:-

The calculations using NumPy are performed using nd-array object which can take any number of dimensions. 
Most commonly used NumPy nd-array is a matrix which takes 2 dimensions.

Array Creation:-

A NumPy nd-array inputs a basic Python list as an argument along with an explicit datatype (for typecasting) as shown below:

In [9]:
# Run the following Code

arr = np.array([2,5,6,8], dtype = int)
arr1 = np.array([2,5,6,8], dtype = float)
arr2 = np.array([2,5,6,8])
print(arr)

# [2 5 6 8]

print(type(arr))

# class 'numpy.ndarray'

print(np.result_type(arr))
print(np.result_type(arr1))
print(np.result_type(arr2))

# int32 
# float64
# int32

[2 5 6 8]
<class 'numpy.ndarray'>
int32
float64
int32


In [ ]:
Here we have used np.array() functions which takes one-two arguements, The input lists and the corresponding datatype. To check
the datatype of the particular NumPy object we have used np.result_type() command.

Most of the time, it is not an intuitive way to pass a list of predefined components. So to counter this, NumPy offers some
commonly used functions to create NumPy object as shown below:

In [24]:
#Run the Following code

#Display a array with 0-10 with the step size of 1.5

print(np.arange(0,10,1.5,dtype = float))
print(np.arange(0,10,1.33,dtype = np.float64))

#arange gives the gives the values from expection start value to end value -- arange(start,end,step)

print(np.linspace(0,500,5,dtype = int))
print(np.linspace(100,500,5,dtype = np.int32))

#similarly, linspace gives values from expected start value to end value but instead of step, it gives total number of values
#to be displayed --- linspace(start,end,total.no.of.values)


[0.  1.5 3.  4.5 6.  7.5 9. ]
[0.   1.33 2.66 3.99 5.32 6.65 7.98 9.31]
[  0 125 250 375 500]
[100 200 300 400 500]


In [ ]:
Now lets understand the basic concepts on Matrix creation:

There are a few ways to create a Matrix using NumPy.
1. Use NumPy array to form a Matrix
2. Use NumPy's inbuilt matrix function
3. Use misc. Functions like zeros(), ones() etc.

In [50]:
#Run the following code
#Method 1 --- array to form a matrix

print(np.array([3,4,6,7,8,9]).reshape(2,3))

#Method 2 --- inbuilt matrix function

print(np.matrix([[1,5],[3,8]]))

#Method 3 --- misc. functions

print(np.zeros((4,3)))
print(np.zeros((4,3), dtype = np.int32))

print(np.eye(4)) #identity matrix
print(np.eye((4), dtype = np.int32))

print(np.ones((4,3)))
print(np.ones((4,3), dtype = np.int32))




[[3 4 6]
 [7 8 9]]
[[1 5]
 [3 8]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
